# Copyright 2023 RobustMQ Team
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http:#www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.


cluster_name = "placement-test"
node_id = 1
addr = "127.0.0.1"
grpc_port = 1228
http_port = 1227
nodes = { 1 = "127.0.0.1:1228" }
runtime_work_threads = 100
data_path = "/tmp/robust/placement-center/data"
log_path = "/tmp/robust/placement-center/logs"
log_segment_size = 1099511627776
log_file_num = 50
heartbeat_timeout_ms = 30000
heartbeat_check_time_ms = 1000

[rocksdb]
max_open_files = 10000
